# Generated by Django 2.2.4 on 2019-09-09 09:10

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=224)),
                ('desc', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=24)),
                ('pic', models.CharField(max_length=24)),
                ('reg_no', models.CharField(max_length=24)),
                ('model', models.CharField(max_length=24)),
                ('prod_year', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('engine_model', models.CharField(blank=True, max_length=24, null=True)),
                ('VIN', models.CharField(blank=True, max_length=30, null=True)),
                ('first_registration', models.DateField()),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel', models.CharField(choices=[('gasoline', 'gasoline'), ('diesel', 'diesel'), ('electricity', 'electricity'), ('hybrid', 'hybrid')], max_length=24)),
                ('power', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('torque', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('engine_capacity', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'ordering': ['manufacturer', 'model', 'engine_capacity'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_tel', models.CharField(blank=True, max_length=24, null=True)),
                ('telegram_chat_id', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('SlackCon', models.CharField(blank=True, max_length=24, null=True)),
                ('FBCon', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milage', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=224, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(to='journal.Owner'),
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic', models.BooleanField()),
                ('important', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=224, null=True)),
                ('desc', models.CharField(blank=True, max_length=224, null=True)),
                ('action_milage_period', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('action_days_period', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('action_end_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=224, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=224, null=True)),
                ('action_popular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.ActionPopular')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_list', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=224, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product', models.CharField(blank=True, max_length=224, null=True)),
                ('ActionTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ActionTemplate')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.File')),
                ('milage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Milage')),
            ],
        ),
    ]
