# Generated by Django 2.0.4 on 2018-04-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontemplate',
            name='title',
        ),
    ]
