# Generated by Django 2.2.4 on 2019-09-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=224, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('todo', models.BooleanField()),
                ('todo_priority', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('attachement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.File')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car')),
            ],
        ),
    ]
