# Generated by Django 2.2.4 on 2019-09-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='todo_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
