# Generated by Django 2.0.4 on 2018-05-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_actiontemplate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milage', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['manufacturer', 'model', 'engine_capacity']},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='manufacurer',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
        migrations.AddField(
            model_name='milage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car'),
        ),
    ]
