# Generated by Django 2.0.4 on 2018-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180504_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reg_no',
            field=models.CharField(default='GWE333', max_length=24),
            preserve_default=False,
        ),
    ]
