# Generated by Django 2.2.6 on 2020-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_note_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='enable_notification',
            field=models.BooleanField(default=True),
        ),
    ]
