# Generated by Django 2.0.4 on 2018-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_car_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic',
            field=models.CharField(default='CRV_III_2007.jpg', max_length=24),
            preserve_default=False,
        ),
    ]
