# Generated by Django 2.0.4 on 2018-05-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_car_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='milage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car'),
        ),
    ]
