# Generated by Django 2.2.13 on 2020-06-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='buy_date',
            new_name='date',
        ),
    ]
