# Generated by Django 2.0.4 on 2018-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_actiontemplate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontemplate',
            name='desc',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
