# Generated by Django 2.0.4 on 2018-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20180514_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontemplate',
            name='action_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
