# Generated by Django 2.0.4 on 2018-05-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_actiontemplate_action_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='milage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Milage'),
        ),
    ]
