# Generated by Django 2.0.4 on 2018-05-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180521_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_popular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.ActionPopular'),
        ),
    ]
