# Generated by Django 2.0.4 on 2018-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20180521_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
