# Generated by Django 2.0.4 on 2018-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_action_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpopular',
            name='title',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='title',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
