# Generated by Django 2.0.4 on 2018-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20180522_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='product',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='product',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='product_quantity',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
