# Generated by Django 2.0.4 on 2018-05-28 15:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0014_auto_20180523_1043'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carowner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='id',
        ),
        migrations.AddField(
            model_name='carowner',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=10, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
