# Generated by Django 2.0.4 on 2018-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20180528_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='surname',
        ),
    ]
