# Generated by Django 2.0.4 on 2018-05-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20180528_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='nick',
        ),
    ]
