# Generated by Django 2.0.4 on 2018-06-11 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_auto_20180528_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milage',
            name='date',
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
