# Generated by Django 2.0.4 on 2018-06-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_milage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=224, null=True)),
                ('desc', models.CharField(blank=True, max_length=224, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='comment',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
    ]
