# Generated by Django 2.0.4 on 2018-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_auto_20180612_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontemplate',
            name='periodic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
