# Generated by Django 2.0.4 on 2018-06-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_actiontemplate_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='telegram_chat_id',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
