# Generated by Django 2.0.4 on 2018-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_owner_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='telegram_chat_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
