# Generated by Django 2.0.4 on 2018-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20180621_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontemplate',
            name='important',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
