# Generated by Django 2.1 on 2018-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_auto_20180822_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
