# Generated by Django 2.1.2 on 2018-10-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_car_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['last_name', 'first_name', 'username']},
        ),
    ]
