# Generated by Django 2.1.2 on 2019-05-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_auto_20181011_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='show_on_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='milage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Milage'),
        ),
    ]
