# Generated by Django 2.1.2 on 2019-05-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_auto_20190529_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='milage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Milage'),
        ),
    ]
