#!/bin/bash
mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -P$MYSQL_PORT  -e "DROP DATABASE IF EXISTS $MYSQL_DATABASE;"
mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -P$MYSQL_PORT  -e "CREATE DATABASE $MYSQL_DATABASE;"