// syntax: https://jenkins.io/doc/book/pipeline/syntax/#agent
pipeline {
  agent {
    dockerfile {
      filename 'jobs/Test/Dockerfile'
    }
  }
  stages {
    stage('Checkout'){
      steps {
        checkout scm
      }
    }
    stage('create database') {
      steps {
        sh '/autotaglibro/jobs/Test/create_database.sh'
      }
    }
    stage('Install pip requierments') {
      steps {
        sh 'pip3 install -r /autotaglibro/requirements.txt'
      }
    }
    stage('Clean migrations') {
      steps {
        sh 'rm -rf /autotaglibro/journal/migrations'
        sh 'python3 manage.py makemigrations'
      }
    }
    stage('Make migrations') {
      steps {
        sh 'python3 manage.py migrate'
      }
    }
    stage('Static code test') {
      steps {
        sh 'python3 manage.py test'
      }
    }
    stage('pylint tests') {
      steps {
        sh 'pylint --load-plugins pylint_django /autotaglibro/journal/'
      }
    }
    stage('pycodestyle tests') {
      steps {
        sh 'pycodestyle /autotaglibro/journal/views.py'
        sh 'pycodestyle /autotaglibro/journal/tests.py'
        sh 'pycodestyle /autotaglibro/journal/forms.py'
        sh 'pycodestyle /autotaglibro/journal/extras.py'
        sh 'pycodestyle /autotaglibro/journal/templatetags/tags.py'
      }
    }
    stage('pydocstyle tests') {
      steps {
        sh 'pydocstyle /autotaglibro/journal/views.py'
        sh 'pydocstyle /autotaglibro/journal/tests.py'
        sh 'pydocstyle /autotaglibro/journal/forms.py'
        sh 'pydocstyle /autotaglibro/journal/extras.py'
        sh 'pydocstyle /autotaglibro/journal/templatetags/tags.py'
      }
    }
    stage('drop database') {
      steps {
        sh '/autotaglibro/jobs/Test/drop_database.sh'
      }
    }
  }
}
