pipeline {
  agent {
    dockerfile {
      filename 'jobs/Test/Dockerfile'
    }
  }
  stages {
    stage('Checkout'){
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'ls /autotaglibro'
      }
    }
  }
}
