Vagrant.configure("2") do |config|

  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :shell, path: "vagrant_bootstrap.sh"
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "base Ansible playbook", type:'ansible' do |ansible|
    ansible.playbook = "playbooks/base_linux.yml"
  end
  config.vm.provision "Auto-taglibro Ansible playbook", type:'ansible' do |ansible|
    ansible.playbook = "playbooks/autotaglibro.yml"
  end
end
